
OBJ	=	ozidataset.obj

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

!IFDEF ZLIB_EXTERNAL_LIB
ZLIB_FLAGS =	-I$(ZLIBDIR)
!ELSE
ZLIB_FLAGS =	-I..\zlib
!ENDIF

EXTRAFLAGS      =        $(ZLIB_FLAGS)

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

